### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Gleteur** [tbitw2549/Clicker-Simulator-V2#2]
The "loadstring(game:HttpGet("https://raw.githubusercontent.com/tbitw2549/TbitLoader/main/Hub"))()" scripte give a 404 error

**Comment by GalacticHypernova** [comment]
The hub is currently under maintenance and will not work. I will republish it as soon as I am done fixing it

**Comment by GalacticHypernova** [comment]
If you want to know more about it and about future  hub updates, you can join my discord server
https://discord.gg/3E4PsPMJM8

**Comment by Gleteur** [comment]
Ok thx for responding.
